#!/usr/bin/env zsh

# This file was generated by antibody (https://github.com/getantibody/antibody).
# Do not edit it directly but instead run "chezmoi cd", update zsh_plugins.txt
# and then run "make plugins".

source /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-fgrosse-SLASH-cdp/init.zsh
fpath+=( /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-fgrosse-SLASH-cdp )
source /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/lib/theme-and-appearance.zsh
source /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/lib/git.zsh
source /home/fgrosse/.local/share/chezmoi/theme/fgrosse.zsh-theme
fpath+=( /home/fgrosse/.local/share/chezmoi/theme )
fpath+=( /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/docker )
fpath+=( /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/httpie )
source /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
fpath+=( /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions )
source /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
fpath+=( /home/fgrosse/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting )
