.PHONY: setup test debug test-build plugins

define ZSH_PLUGINS_FILE_HEADER
#!/usr/bin/env zsh

# This file was generated by antibody (https://github.com/getantibody/antibody).
# Do not edit it directly but instead run "chezmoi cd", update zsh_plugins.txt
# and then run "make plugins".

endef
export ZSH_PLUGINS_FILE_HEADER

test: test-build
	docker run -it --rm chezmoi-test

debug: test-build
	docker run -it --rm chezmoi-test bash

test-build:
	docker build -t chezmoi-test -f ./test/Dockerfile .

setup:
	./setup.sh

plugins:
	echo -e "$$ZSH_PLUGINS_FILE_HEADER" > dot_zsh_plugins.sh
	antibody bundle < zsh_plugins.txt  >> dot_zsh_plugins.sh
	chezmoi apply
